import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-6 py-8 max-w-4xl">
        <div className="flex items-center gap-4 mb-8">
          <Link href="/">
            <Button variant="ghost" size="sm" className="flex items-center gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Button>
          </Link>
        </div>

        <div className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

          <p className="text-muted-foreground mb-6">
            <strong>Last updated:</strong> {new Date().toLocaleDateString()}
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Careerate's AI-powered development platform ("Service"), you agree to be bound by these
              Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
            <p>
              Careerate provides an AI-powered platform that combines code generation with intelligent hosting and project
              management capabilities. Our Service allows users to:
            </p>
            <ul className="list-disc pl-6 mt-4">
              <li>Generate code using natural language descriptions</li>
              <li>Manage and deploy applications</li>
              <li>Collaborate on development projects</li>
              <li>Access AI-powered development tools</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>

            <h3 className="text-xl font-medium mb-3">3.1 Account Creation</h3>
            <p>
              You may create an account using GitHub or Microsoft OAuth. You are responsible for maintaining
              the confidentiality of your account credentials.
            </p>

            <h3 className="text-xl font-medium mb-3 mt-6">3.2 Account Responsibilities</h3>
            <ul className="list-disc pl-6">
              <li>Provide accurate and complete information</li>
              <li>Keep your account information up to date</li>
              <li>Maintain the security of your account</li>
              <li>Notify us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">4. Acceptable Use</h2>

            <h3 className="text-xl font-medium mb-3">4.1 Permitted Uses</h3>
            <p>You may use our Service for legitimate software development and business purposes.</p>

            <h3 className="text-xl font-medium mb-3 mt-6">4.2 Prohibited Uses</h3>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 mt-4">
              <li>Generate malicious, harmful, or illegal code</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Distribute malware, viruses, or harmful content</li>
              <li>Attempt to reverse engineer or hack our platform</li>
              <li>Use the Service for cryptocurrency mining</li>
              <li>Spam or send unsolicited communications</li>
              <li>Impersonate others or provide false information</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>

            <h3 className="text-xl font-medium mb-3">5.1 Your Content</h3>
            <p>
              You retain ownership of the code and content you create using our Service. By using our Service,
              you grant us a limited license to process and store your content as necessary to provide the Service.
            </p>

            <h3 className="text-xl font-medium mb-3 mt-6">5.2 Our Platform</h3>
            <p>
              Careerate and its underlying technology, including but not limited to our AI models, algorithms,
              and platform infrastructure, are protected by intellectual property laws.
            </p>

            <h3 className="text-xl font-medium mb-3 mt-6">5.3 AI-Generated Code</h3>
            <p>
              Code generated by our AI models is provided "as is." While you may use generated code in your
              projects, you are responsible for ensuring it meets your requirements and doesn't infringe on
              third-party rights.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">6. Privacy and Data Protection</h2>
            <p>
              Your privacy is important to us. Our collection and use of personal information is governed by
              our <Link href="/privacy" className="text-primary underline">Privacy Policy</Link>,
              which is incorporated into these Terms by reference.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">7. Billing and Payments</h2>

            <h3 className="text-xl font-medium mb-3">7.1 Subscription Plans</h3>
            <p>
              We offer various subscription plans with different features and usage limits. Billing terms
              are specified at the time of subscription.
            </p>

            <h3 className="text-xl font-medium mb-3 mt-6">7.2 Payment Terms</h3>
            <ul className="list-disc pl-6">
              <li>Fees are charged in advance on a recurring basis</li>
              <li>All fees are non-refundable unless otherwise stated</li>
              <li>We may update pricing with 30 days notice</li>
              <li>Accounts may be suspended for non-payment</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">8. Service Availability</h2>
            <p>
              While we strive to maintain high availability, we do not guarantee uninterrupted access to our Service.
              We may perform maintenance, updates, or temporary suspensions as needed.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">9. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL
              WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY,
              FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">10. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CAREERATE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA,
              OR OTHER INTANGIBLE LOSSES.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">11. Indemnification</h2>
            <p>
              You agree to indemnify and hold Careerate harmless from any claims, damages, or expenses arising
              from your use of the Service or violation of these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">12. Termination</h2>
            <p>
              We may terminate or suspend your account at any time for violation of these Terms. You may
              terminate your account at any time through your account settings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction
              where Careerate is incorporated, without regard to conflict of law principles.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">14. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of material changes
              via email or through our platform. Continued use of the Service after changes indicates acceptance
              of the updated Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">15. Contact Information</h2>
            <p>
              If you have questions about these Terms, please contact us at:
            </p>
            <div className="mt-4 p-4 bg-muted rounded-lg">
              <p><strong>Email:</strong> legal@careerate.com</p>
              <p><strong>Address:</strong> [Company Address]</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}